services:
  backend:
    build: ./backend
    env_file: ./backend/.env
    ports:
      - "3001:3001"
    volumes:
      - backend-logs:/app/logs

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend
      - node-exporter

  node-exporter:
   image: prom/node-exporter:latest
   ports:
    - "9100:9100"
   volumes:
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    - /:/rootfs:ro
   command:
    - '--path.procfs=/host/proc'
    - '--path.sysfs=/host/sys'
    - '--path.rootfs=/rootfs'
    - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

  grafana:
    image: grafana/grafana
    ports:
      - "3300:3000"
    depends_on:
      - prometheus

volumes:
  backend-logs: